# 設定 server port
server.port=9458
spring.application.name=backend

# PostgreSQL 資料庫連線設定
spring.datasource.url=jdbc:postgresql://10.177.82.23:5432/rd_eng_solve
spring.datasource.username=draw_worker
spring.datasource.password=Aa@123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=rd_drinks
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
